- name: "Update the system ..."
  yum:
    name: "*"
    state: latest
  become: yes
  tags: 
    - system

- name: "Install Development Tools ..."
  yum:
   name: "@Development Tools"
   state: latest
  become: yes
  tags: 
    - Development Tools
    - optional]

- name: "Dowload RPM script ...."
  get_url:
    url: "{{ rpm_base_url }}"
    dest: $HOME
    mode: 0770
  become: yes
  tags: 
    - nodejs

- name: "Install nodejs and NPM package..."
  shell: "./{{ rpm_base_url | urlsplit('path') }}"
  args:
    chdir: $HOME
  become: yes
  tags:
    - package
    - nodejs

- name: "Installing Nodejs et NPM ..."
  yum:
    name: nodejs
    state: latest
  become: yes
  tags: 
    - nodejs
    - npm
