- name: "Update the system ..."
  apt:
    name: "*"
    state: latest
  tags: ["System"]

- name: "Install Development Tools ..."
  apt:
   name: build-essential
   state: latest
  tags: ["Development Tools","optional"]

- name: "Dowload RPM script ...."
  get_url:
    url: "{{ deb_base_url }}"
    dest: $HOME
    mode: 0770
  tags: ["nodejs"]

- name: "Install nodejs and NPM package..."
  shell: "./{{ deb_base_url | urlsplit('path') }}"
  args:
    chdir: $HOME 
  changed_when: false
  tags: ["package","nodejs"]
   

- name: "Installing Nodejs et NPM ..."
  deb: nodejs
  state: latest
  tags: ["nodejs"]